Repository neo4j-labs/neodash, pull requests merged in 2022-09, with the labels that each got.

#196 Added extensions for table report, optional markdown descriptions (pop-ups), deep-linking pages and line-chart customizations
  docs/modules/ROOT/pages/developer-guide/standalone-mode.adoc
  docs/modules/ROOT/pages/user-guide/reports/bar-chart.adoc
  docs/modules/ROOT/pages/user-guide/reports/choropleth.adoc
  docs/modules/ROOT/pages/user-guide/reports/circle-packing.adoc
  docs/modules/ROOT/pages/user-guide/reports/graph.adoc
  docs/modules/ROOT/pages/user-guide/reports/iframe.adoc
  docs/modules/ROOT/pages/user-guide/reports/line-chart.adoc
  docs/modules/ROOT/pages/user-guide/reports/map.adoc
  docs/modules/ROOT/pages/user-guide/reports/markdown.adoc
  docs/modules/ROOT/pages/user-guide/reports/parameter-select.adoc
  docs/modules/ROOT/pages/user-guide/reports/pie-chart.adoc
  docs/modules/ROOT/pages/user-guide/reports/raw-json.adoc
  docs/modules/ROOT/pages/user-guide/reports/sankey.adoc
  docs/modules/ROOT/pages/user-guide/reports/single-value.adoc
  docs/modules/ROOT/pages/user-guide/reports/sunburst.adoc
  docs/modules/ROOT/pages/user-guide/reports/table.adoc
  docs/modules/ROOT/pages/user-guide/reports/treemap.adoc
  src/application/ApplicationThunks.ts
  src/card/view/CardView.tsx
  src/card/view/CardViewHeader.tsx
  src/chart/TableChart.tsx
  src/chart/visualizations/LineVisualization.tsx
  src/component/field/Field.tsx
  src/component/field/Setting.tsx
  src/config/ReportConfig.tsx
  src/settings/SettingsThunks.ts
Labels: Ready To Merge

#206 Cycle detection
  src/chart/visualizations/SankeyVisualization.tsx
  src/chart/visualizations/Utils.ts
Labels: bug, awaiting feedback

#200 Adding support for default values in parameter select reports
  src/chart/ParameterSelectionChart.tsx
  src/config/ReportConfig.tsx
Labels: Ready To Merge

#201 Added setting to customize a map provider for map visualizations
  src/chart/MapChart.tsx
  src/config/ReportConfig.tsx
Labels: Ready To Merge

#207 Adding Radar Charts
  docs/modules/ROOT/images/radar.png
  docs/modules/ROOT/pages/user-guide/reports/radar.adoc
  docs/package-lock.json
  docs/package.json
  package.json
  src/chart/RadarChart.tsx
  src/chart/visualizations/RadarVisualization.tsx
  src/config/ExampleConfig.ts
  src/config/ReportConfig.tsx
  src/report/ReportQueryRunner.ts
  src/report/ReportRecordProcessing.tsx
  yarn.lock
Labels: awaiting feedback
