Repository neo4j-labs/neodash, pull requests merged in 2023-07, with the labels that each got.

#482 Final changes after the 2.3.0 Pre-release
  docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
  docs/modules/ROOT/pages/developer-guide/styleConfiguration.adoc
  docs/modules/ROOT/pages/user-guide/extensions/workflows.adoc
  src/chart/graph/component/button/GraphChartFitViewButton.tsx
  src/dashboard/Dashboard.tsx
  src/extensions/ExtensionConfig.tsx
  src/extensions/query-translator/clients/ModelClient.ts
  src/extensions/query-translator/clients/const.ts
  src/extensions/query-translator/component/OverrideCardQueryEditor.tsx
  src/extensions/query-translator/component/QueryTranslator.tsx
  src/extensions/query-translator/util/Util.ts
  src/extensions/state/ExtensionReducer.ts
  src/extensions/state/ExtensionSelectors.ts
  src/report/ReportQueryRunner.ts
  src/settings/SettingsThunks.ts
Labels: documentation, 2.3

#514 Parameter support on natural language queries
  src/extensions/query-translator/clients/OpenAi/OpenAiClient.ts
Labels: enhancement

#536 Fix/issue 534
  README.md
  src/chart/table/TableChart.tsx
  src/report/ReportRecordProcessing.tsx
Labels: bug
