Repository neo4j-labs/neodash, pull requests merged in 2024-02, with the labels that each got.

#779 Fixed issue where dashboards were marked as draft incorrectly on selection change
  src/application/ApplicationReducer.ts
Labels: Ready To Merge, 2.4.3

#777 Update Configuration Docs
  docs/modules/ROOT/pages/developer-guide/configuration.adoc
Labels: Ready To Merge, 2.4.3

#784 Fix - Added standalonePasswordWarningHidden option to config-entrypoint.sh
  scripts/config-entrypoint.sh
Labels: 2.4.3

#769 Cypress e2e component testing
  .gitignore
  cypress/e2e/bar_chart.cy.js
  cypress/e2e/start_page.cy.js
  cypress/e2e/table.cy.js
  cypress/support/commands.js
  src/card/settings/CardSettingsContent.tsx
Labels: 2.4.3, cypress

#773 Update quickstart.adoc to point to Aura console
  docs/modules/ROOT/pages/quickstart.adoc
Labels: 2.4.3

#782 Fixing wrong behaviour in GraphChart report Action
  src/extensions/actions/ActionsRuleCreationModal.tsx
Labels: 2.4.3

#768 Fix/clipping examples
  src/extensions/text2cypher/component/model-examples/ExampleDisplayTable.tsx
Labels: Ready To Merge, 2.4.3

#760 Bug/bar chart on hover
  src/chart/bar/BarChart.tsx
Labels: 2.4.3

#790 adding symbol to force utf-8 casting in Excel
  src/chart/ChartUtils.ts
Labels: 2.4.3

#794 Fix/parameter select
  cypress/e2e/bar_chart.cy.js
  cypress/e2e/table.cy.js
  src/chart/parameter/component/DateParameterSelect.tsx
  src/chart/parameter/component/NodePropertyParameterSelect.tsx
  yarn.lock
Labels: 2.4.3

#611 Handle token expiration in SSO
  package.json
  src/application/ApplicationActions.ts
  src/application/ApplicationReducer.ts
  src/application/ApplicationThunks.ts
  src/component/sso/SSOUtils.ts
  src/dashboard/Dashboard.tsx
  yarn.lock
Labels: 2.4.3

#799 Added release notes for 2.4.3 release
  .github/workflows/master-deployment.yml
  Dockerfile
  changelog.md
  docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
  package.json
  release-notes.md
  src/modal/AboutModal.tsx
Labels: 2.4.3

#793 Add RBAC extensions and dashboard access management
  cypress/e2e/start_page.cy.js
  docs/modules/ROOT/images/dashboardaccesscontrol.png
  docs/modules/ROOT/images/dashboardnew.png
  docs/modules/ROOT/images/dashboardnewsettings.png
  docs/modules/ROOT/images/rolelabelmodal.png
  docs/modules/ROOT/images/rolesmenu.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/user-guide/access-control.adoc
  docs/modules/ROOT/pages/user-guide/dashboards.adoc
  docs/modules/ROOT/pages/user-guide/extensions/access-control-management.adoc
  docs/modules/ROOT/pages/user-guide/extensions/index.adoc
  public/accesscontrol2.jpg
  src/dashboard/header/DashboardTitle.tsx
  src/dashboard/sidebar/DashboardSidebar.tsx
  src/dashboard/sidebar/menu/DashboardSidebarDashboardMenu.tsx
  src/dashboard/sidebar/modal/DashboardSidebarAccessModal.tsx
  src/extensions/ExtensionConfig.tsx
  src/extensions/rbac/RBACManagementLabelButton.tsx
  src/extensions/rbac/RBACManagementMenu.tsx
  src/extensions/rbac/RBACManagementModal.tsx
  src/extensions/rbac/RBACUtils.ts
Labels: 2.4.3

#800 adding migration for report action fix
  src/dashboard/DashboardReducer.ts
  src/dashboard/DashboardThunks.ts
Labels: 2.4.3

#801 Report actions - fixing forEach on null variable
  src/dashboard/DashboardThunks.ts
Labels: 2.4.3

#798 2.4.3 Release
  .github/workflows/master-deployment.yml
  .gitignore
  Dockerfile
  changelog.md
  cypress/e2e/bar_chart.cy.js
  cypress/e2e/start_page.cy.js
  cypress/e2e/table.cy.js
  cypress/support/commands.js
  docs/modules/ROOT/images/dashboardaccesscontrol.png
  docs/modules/ROOT/images/dashboardnew.png
  docs/modules/ROOT/images/dashboardnewsettings.png
  docs/modules/ROOT/images/rolelabelmodal.png
  docs/modules/ROOT/images/rolesmenu.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/developer-guide/configuration.adoc
  docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
  docs/modules/ROOT/pages/quickstart.adoc
  docs/modules/ROOT/pages/user-guide/access-control.adoc
  docs/modules/ROOT/pages/user-guide/dashboards.adoc
  docs/modules/ROOT/pages/user-guide/extensions/access-control-management.adoc
  docs/modules/ROOT/pages/user-guide/extensions/index.adoc
  docs/preview.yml
  gallery/yarn.lock
  package.json
  public/accesscontrol2.jpg
  release-notes.md
  scripts/config-entrypoint.sh
  src/application/ApplicationActions.ts
  src/application/ApplicationReducer.ts
  src/application/ApplicationThunks.ts
  src/card/settings/CardSettingsContent.tsx
  src/chart/ChartUtils.ts
  src/chart/bar/BarChart.tsx
  src/chart/parameter/component/DateParameterSelect.tsx
  src/chart/parameter/component/NodePropertyParameterSelect.tsx
  src/chart/table/TableChart.tsx
  src/component/sso/SSOUtils.ts
  src/dashboard/Dashboard.tsx
  src/dashboard/DashboardReducer.ts
  src/dashboard/DashboardThunks.ts
  src/dashboard/header/DashboardTitle.tsx
  src/dashboard/sidebar/DashboardSidebar.tsx
  src/dashboard/sidebar/menu/DashboardSidebarDashboardMenu.tsx
  src/dashboard/sidebar/modal/DashboardSidebarAccessModal.tsx
  src/extensions/ExtensionConfig.tsx
  src/extensions/actions/ActionsRuleCreationModal.tsx
  src/extensions/rbac/RBACManagementLabelButton.tsx
  src/extensions/rbac/RBACManagementMenu.tsx
  src/extensions/rbac/RBACManagementModal.tsx
  src/extensions/rbac/RBACUtils.ts
  src/extensions/text2cypher/component/model-examples/ExampleDisplayTable.tsx
  src/index.pcss
  src/modal/AboutModal.tsx
  yarn.lock
Labels: 2.4.3
