Repository neo4j-labs/neodash, pull requests merged in 2024-04, with the labels that each got.

#857 #856 Disable auto-sorting of Cypher query Parameter Select
  src/chart/parameter/ParameterSelectionChart.tsx
  src/chart/parameter/component/NodePropertyParameterSelect.tsx
  src/chart/parameter/component/ParameterSelect.ts
  src/chart/parameter/component/QueryParameterSelect.tsx
Labels: Ready To Merge, 2.4.5

#855 #848 Render HTML strings
  package.json
  src/chart/graph/component/GraphEntityInspectionTable.tsx
  src/chart/table/TableChart.tsx
  src/report/ReportRecordProcessing.tsx
  yarn.lock
Labels: Ready To Merge, 2.4.5

#854 Update role selector menu + more robust user updates
  src/extensions/rbac/RBACManagementMenu.tsx
  src/extensions/rbac/RBACUtils.ts
Labels: Ready To Merge, 2.4.5

#852 #789 wrap text table
  public/style.css
  src/chart/table/TableChart.tsx
Labels: Ready To Merge, 2.4.5

#849 fixes bug where arrays are passed as [object Object]
  src/chart/ChartUtils.ts
Labels: Ready To Merge, 2.4.5

#863 Fix padding in compact table with report actions
  src/chart/table/TableChart.tsx
Labels: 2.4.5

#864 html render rollback due to too many bugs
  src/chart/graph/component/GraphEntityInspectionTable.tsx
  src/chart/table/TableChart.tsx
  src/report/ReportRecordProcessing.tsx
Labels: 2.4.5

#872 Make wrapping in table optional, enabled by default
  src/chart/table/TableChart.tsx
  src/config/ReportConfig.tsx
Labels: Ready To Merge, 2.4.6

#873 Fixed issues where cross database dashboard sharing always reverted back to the default database
  src/application/ApplicationActions.ts
  src/application/ApplicationThunks.ts
Labels: Ready To Merge, 2.4.6

#876 Added option to define style config using environment variables for the Docker image
  docs/modules/ROOT/pages/developer-guide/style-configuration.adoc
  scripts/config-entrypoint.sh
Labels: 2.4.6

#877 Added release notes for 2.4.6
  .github/workflows/master-deployment.yml
  Dockerfile
  changelog.md
  docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
  package.json
  release-notes.md
  src/modal/AboutModal.tsx
Labels: 2.4.6

#878 2.4.6 Release
  .github/workflows/master-deployment.yml
  Dockerfile
  changelog.md
  docs/modules/ROOT/pages/developer-guide/deploy-a-build.adoc
  docs/modules/ROOT/pages/developer-guide/style-configuration.adoc
  package.json
  release-notes.md
  scripts/config-entrypoint.sh
  src/application/ApplicationActions.ts
  src/application/ApplicationThunks.ts
  src/chart/table/TableChart.tsx
  src/config/ReportConfig.tsx
  src/modal/AboutModal.tsx
  src/report/ReportRecordProcessing.tsx
Labels: 2.4.6
