Repository neo4j-labs/neodash, pull requests merged in 2024-11, with the labels that each got.

#951 Improve method for checking "low" property existence in downloadCSV f…
  src/chart/ChartUtils.ts
Labels: bug, 2.4.9

#946 Update configuration.adoc
  docs/modules/ROOT/pages/developer-guide/configuration.adoc
Labels: 2.4.9

#944 Feature/rule based styling table colouring
  src/chart/table/TableChart.tsx
  src/extensions/styling/StyleRuleCreationModal.tsx
  src/extensions/styling/StyleRuleEvaluator.ts
Labels: 2.4.9

#943 Bugfix/array table wrap
  src/report/ReportRecordProcessing.tsx
Labels: 2.4.9

#918 adding param to manage SSO redirection
  src/application/ApplicationThunks.ts
Labels: 2.4.9

#895 Add possibility to hide Y axes and grid lines in BarChart
  .eslintrc.json
  cypress.config.ts
  cypress/Page.js
  cypress/e2e/bar_chart.cy.js
  cypress/e2e/charts/array.cy.js
  cypress/e2e/charts/bar.cy.js
  cypress/e2e/charts/table.cy.js
  cypress/e2e/start_page.cy.js
  cypress/e2e/utils.js
  cypress/index.js
  cypress/support/commands.js
  docs/modules/ROOT/pages/developer-guide/style-configuration.adoc
  package.json
  src/chart/bar/BarChart.tsx
  src/config/ReportConfig.tsx
Labels: enhancement, 2.4.9

#893 Markdown tables not rendered #836
  package.json
  src/chart/markdown/MarkdownChart.tsx
  src/index.pcss
  yarn.lock
Labels: 2.4.9

#906 Current Users or ALL Users getting deleted in an Update
  src/extensions/rbac/RBACManagementModal.tsx
  src/extensions/rbac/RBACUtils.ts
Labels: 2.4.9

#971 [Feature #884] Helm chart for Kubernetes deployments PR#902
  docs/modules/ROOT/pages/developer-guide/build-and-run.adoc
  k8s-deploy/neodash/.helmignore
  k8s-deploy/neodash/Chart.yaml
  k8s-deploy/neodash/README.md
  k8s-deploy/neodash/templates/NOTES.txt
  k8s-deploy/neodash/templates/_helpers.tpl
  k8s-deploy/neodash/templates/deployment.yaml
  k8s-deploy/neodash/templates/hpa.yaml
  k8s-deploy/neodash/templates/ingress.yaml
  k8s-deploy/neodash/templates/service.yaml
  k8s-deploy/neodash/templates/serviceaccount.yaml
  k8s-deploy/neodash/templates/tests/test-connection.yaml
  k8s-deploy/neodash/values.yaml
  k8s-deploy/sample-k8s-yamls/deployment.yaml
  k8s-deploy/sample-k8s-yamls/service.yaml
Labels: 2.4.9

#822 Feat/forms button improvements
  cypress/e2e/start_page.cy.js
  src/extensions/forms/chart/NeoForm.tsx
  src/utils/parameterUtils.ts
Labels: 2.4.9

#894 Migrate DataGrid to 7x
  package.json
  src/chart/table/TableActionsHelper.ts
  src/chart/table/TableChart.tsx
  src/index.pcss
  yarn.lock
Labels: 2.4.9
