Repository neo4j-labs/neodash, pull requests merged in 2025-02, with the labels that each got.

#1020 Fixed booleans for parameter select (#953)
  src/chart/parameter/component/NodePropertyParameterSelect.tsx
Labels: bug, 2.4.10

#999 Fix/dark mode table header
  public/style.css
Labels: bug, 2.4.10

#1002 Patch FAQ on supportability
  docs/modules/ROOT/pages/user-guide/faq.adoc
Labels: 2.4.10

#1005 adding new logos
  public/neo4j-icon-color-full.png
  public/neo4j-icon-color.png
  public/neo4j-icon.png
Labels: 2.4.10

#1008 Fix value.low existence check when value is not an Object
  src/chart/ChartUtils.ts
Labels: bug, 2.4.10

#1014 Removed the introduced autoPageSize flag because it will default to 0 #992
  src/chart/table/TableChart.tsx
Labels: charts, 2.4.10

#1009 fixing strange param behaviour with sso
  src/application/ApplicationThunks.ts
  src/component/sso/SSOLoginButton.tsx
Labels: bug, priority, 2.4.10

#1038 Fix/1037 line rule based styling
  src/chart/line/LineChart.tsx
  src/chart/table/TableChart.tsx
  src/extensions/styling/StyleRuleEvaluator.ts
Labels: bug, charts, 2.4.10

#1039 Fix/default color scheme bar chart
  src/chart/bar/BarChart.tsx
Labels: bug, charts, 2.4.10
